apiVersion: apps/v1
kind: Deployment
metadata:
  name:  grow
  namespace: app
  labels:
    app:  grow
spec:
  selector:
    matchLabels:
      app: grow
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  grow
    spec:
      serviceAccountName: grow
      containers:
      - name:  grow
        image: 353615901360.dkr.ecr.us-east-1.amazonaws.com/grow:v1
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "45"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                curl -f http://localhost:8080/health || exit 1
          initialDelaySeconds: 5
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                curl -f http://localhost:8080/health || exit 1
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name:  grow
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
          
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: grow
  namespace: app
spec:
  selector:
    app: grow
  type: ClusterIP
  ports:
  - name: grow
    protocol: TCP
    port: 8080
    targetPort: 8080
---

